### ISSUE TITLE
wrong arguments passed to the callback

### ISSUE THREAD

**Issue by hugebdu** [Kikobeats/map-values-deep#1]
lodash's [mapValues](https://lodash.com/docs/4.17.11#mapValues) callback accepts three arguments, your example mentions the key (`const square = (value, key) => value * value`) but looks like [you're passing](https://github.com/Kikobeats/map-values-deep/blob/master/index.js#L9) only the value

**Comment by Kikobeats** [comment]
hmmm

```
_.mapValues(object, [iteratee=_.identity])
```

The docs are saying it accepts two arguments 🤔 what is the third argument? can you make a PR to see it on action?

**Comment by hugebdu** [comment]
> The iteratee is invoked with three arguments: (value, key, object).

from [lodash docs](https://lodash.com/docs/4.17.11#mapValues)
