### ISSUE TITLE
ES6 export/import

### ISSUE THREAD

**Issue by brysbra** [Kikobeats/map-values-deep#3]
Very handy library! 👍 

I tried importing using ES6 style imports.

`import mapValuesDeep from 'map-values-deep';`

Resulted in:

![image](https://user-images.githubusercontent.com/4086154/63944805-c3600880-ca61-11e9-8689-86086d1ba011.png)

`import { mapValuesDeep } from 'map-values-deep';`

Resulted in:

![image](https://user-images.githubusercontent.com/4086154/63944874-eab6d580-ca61-11e9-9645-b89863f1e1da.png)

`import * as mapValuesDeep from 'map-values-deep';`

^ This worked.

Have you considered exporting using ES6 style exports?

`export default mapValuesDeep` instead of `module.exports = mapValuesDeep`

**Comment by Kikobeats** [comment]
Hello,

I can't add `export default mapValuesDeep` since Node.js doesn't understand ES6 modules.
